# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # LUKS2 full disk encryption. Placeholder UUIDs — fill in the real ones
  # during the in-place reencrypt (cryptsetup luksUUID <partition>); the
  # btrfs filesystem UUID below survives the conversion unchanged.
  boot.initrd.luks.devices = {
    cryptroot = {
      device = "/dev/disk/by-uuid/REPLACE-WITH-LUKS-UUID-ROOT";
      allowDiscards = true; # SSD TRIM through dm-crypt
      bypassWorkqueues = true; # better NVMe latency
    };
    cryptswap = {
      device = "/dev/disk/by-uuid/REPLACE-WITH-LUKS-UUID-SWAP";
      allowDiscards = true;
      bypassWorkqueues = true;
    };
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2d1d7562-8135-4800-b528-7a8cf7cdbccf";
      fsType = "btrfs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/2d1d7562-8135-4800-b528-7a8cf7cdbccf";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/2d1d7562-8135-4800-b528-7a8cf7cdbccf";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2266-7163";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/cryptswap"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
