# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # LUKS2 full disk encryption (retrofitted in place with `cryptsetup
  # reencrypt`). These are the LUKS container UUIDs; the btrfs filesystem
  # UUID below survived the conversion unchanged.
  boot.initrd.luks.devices = {
    cryptroot = {
      device = "/dev/disk/by-uuid/62698cfb-75d8-4bec-a56d-4006bb615457";
      allowDiscards = true; # SSD TRIM through dm-crypt
      bypassWorkqueues = true; # better NVMe latency
    };
    cryptswap = {
      device = "/dev/disk/by-uuid/66b9e7df-05cd-4038-8011-db8c0b3a2560";
      allowDiscards = true;
      bypassWorkqueues = true;
    };
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2d1d7562-8135-4800-b528-7a8cf7cdbccf";
      fsType = "btrfs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/2d1d7562-8135-4800-b528-7a8cf7cdbccf";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/2d1d7562-8135-4800-b528-7a8cf7cdbccf";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2266-7163";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/cryptswap"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
